---
name: IO-Async-Loop-Ppoll
version: 0.06
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: 'use C<IO::Async> with C<ppoll(2)>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  IO::Async::LoopTests: 0.24
  Test::More: 0
requires:
  IO::Async: 0.24
  IO::Async::Loop::Poll: 0.2
  IO::Ppoll: 0.05
configure_requires:
  Module::Build: 0.35
provides:
  IO::Async::Loop::Ppoll:
    file: lib/IO/Async/Loop/Ppoll.pm
    version: 0.06
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
